/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ticketreversation;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class CancellationFrame extends javax.swing.JFrame {

    /**
     * Creates new form CancellationFrame
     */
    public CancellationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        revNum = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cancellation");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setText("Home");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(78, 57, 42, 21);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton2.setText("Ticketing");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(228, 57, 64, 21);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 3, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancellation");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(485, 57, 100, 21);

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton4.setText("Account");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(671, 60, 58, 15);
        jPanel3.add(jLabel3);
        jLabel3.setBounds(545, 51, 0, 0);
        jPanel3.add(jLabel5);
        jLabel5.setBounds(304, 46, 0, 0);
        jPanel3.add(jLabel2);
        jLabel2.setBounds(714, 51, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon("Photos\\Un Choosen Home.png")); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(87, 30, 25, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon("Photos\\Un Choosen Ticket.png")); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(245, 27, 30, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("Photos\\Choosen Cancellation.png")); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(518, 27, 30, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("Photos\\Un Choosen Account.png")); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(686, 29, 27, 27);

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setIcon(new javax.swing.ImageIcon("Photos\\Un Choosen Review.png")); // NOI18N
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(365, 20, 50, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 800, 92);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("copyright © Ticket Reversation App all rights reserved");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(246, 433, 318, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setText("Enter Reversation Number");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(290, 210, 240, 20);

        revNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revNumActionPerformed(evt);
            }
        });
        jPanel1.add(revNum);
        revNum.setBounds(290, 240, 240, 30);

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Cancel Reversation");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(290, 280, 240, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//زر الهوم
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Home home = new Home();
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
//زر واجهة الحجز
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TicketingFrame ticketingFrame = new TicketingFrame();
        ticketingFrame.setVisible(true);
        ticketingFrame.pack();
        ticketingFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
//زر واجهة إلغاء الحجز
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
//زر الحساب
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
        //منطق ظهور معلومات الحجوزات في حساب المستخدم
           AccountFrame accountFrame = new AccountFrame();
            
            Ticketing ticketing = new Ticketing();
            ticketing.displayAccountInfo();
        //الوصول للملف النصي للحساب وقراءة المعلومات منه
            File f = new File("Account\\account.txt");
            Scanner in1 = new Scanner(new FileReader(f));
            while (in1.hasNextLine()) {
                AccountFrame.AccountInfo.append(in1.nextLine()+"\n");
            }
            in1.close();
            //تفريغ الملف حتى لا تتكرر البيانات نفسها اكثر من مرة 
            PrintWriter pw = new PrintWriter(f);
            pw.print("");
            pw.close();
            //منطق ظهور الاسم الكامل للمستخدم في صفحة الحساب
            Scanner in = new Scanner(new FileReader("Users\\"+TicketReversation.u.getUsername()+"\\Info.txt"));
            in.nextLine();
            String s = in.nextLine().substring(9);
            in.close();
            //كتابة الاسم الكامل في صفحة الحساب
            accountFrame.fn.setText(s);
            accountFrame.setVisible(true);
            accountFrame.pack();
            accountFrame.setLocationRelativeTo(null);
            this.dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CancellationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void revNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_revNumActionPerformed
//زر إلغاء الحجز
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        try {
            //الوصول لمعلومات الحجز
            File f1 = new File("Users\\"+TicketReversation.u.getUsername()+"\\"+revNum.getText()+".txt");
            //معالجة حالة ان يكون رقم الحجز غير موجود عند المستخدم او ان يكون الملف فارغ
            if(!f1.exists() || f1.length()==0)
            {
                JOptionPane.showMessageDialog(null,"The Entered Reversation Number Is Wrong ❌");
            }
            else{
            //قراءة معلومات الحجز
            Scanner in = new Scanner(new FileReader(f1));
            in.useDelimiter(",");
            String movieName = in.next();
            String hall = in.next();
            String d = in.next();
            in.close();
            //ملف وقت العرض
            File f2 = new File("Cinema\\"+hall+"\\"+movieName+"\\"+d+".txt");
            //تطبيق عملية إلغاءالحجز
            Ticketing t = new Ticketing(TicketReversation.u.getUsername(),revNum.getText(),f1,f2);
            t.cancelReservation();
            JOptionPane.showMessageDialog(null,"The Cancellation Has Done Successfully ✔");
            //الانتقال لواجهة الهوم
            Home home = new Home();
            home.setVisible(true);
            home.pack();
            home.setLocationRelativeTo(null);
            this.dispose();
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CancellationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CommentsOrFeedback commentsOrFeedback = new CommentsOrFeedback();
        try {
            //ملف التعليقات
            File f = new File("Comments\\Review.txt");
            Scanner in = new Scanner(new FileReader(f));
            //ظهور التعليقات في المنطقة المخصصة
            while(in.hasNextLine())
            {
                commentsOrFeedback.reviewsArea.append(in.nextLine()+"\n");
            }
            
            in.close();

            commentsOrFeedback.setVisible(true);
            commentsOrFeedback.pack();
            commentsOrFeedback.setLocationRelativeTo(null);
            this.dispose();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AccountFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancellationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancellationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancellationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancellationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancellationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JTextField revNum;
    // End of variables declaration//GEN-END:variables
}
