/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ticketreversation;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class ChangePasswordFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChangePasswordFrame
     */
    public ChangePasswordFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        oldPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        newPass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Change Password");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(230, 7, 380, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 70);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel2.setText("Old Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 140, 150, 23);

        oldPass.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        oldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPassActionPerformed(evt);
            }
        });
        jPanel1.add(oldPass);
        oldPass.setBounds(300, 170, 220, 23);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel3.setText("New Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 200, 150, 23);

        newPass.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        newPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassActionPerformed(evt);
            }
        });
        jPanel1.add(newPass);
        newPass.setBounds(300, 230, 220, 23);

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Back To Home >");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 310, 220, 40);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(300, 260, 220, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("copyright © Ticket Reversation App all rights reserved");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(246, 433, 318, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oldPassActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_oldPassActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_oldPassActionPerformed

    private void newPassActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newPassActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_newPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        Home home = new Home();
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null);
        this.dispose();
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        try {
            // كلمة السر القديمة المدخلة من قبل المستخدم
            String oldPassword = oldPass.getText();
            // كلمة السر الجديدة المدخلة من قبل المستخدم
            String newPassword = newPass.getText();
            // Users->user_name->Info.txt
            File f = new File("Users\\" + TicketReversation.u.getUsername() + "\\Info.txt");
            Scanner in = new Scanner(new FileReader(f));
            // كلمة مرور المستخدم القديمة
            String password = in.nextLine().substring(9);
            // الاسم الكامل للمستخدم كي لا يضيع منا
            String fullName = in.nextLine().substring(9);

            in.close();

            // معالجة الاستثناءات المحتملة
            // ان تكون كلمة السر القديمة المدخلة لا تساوي كلمة السرالحالية
            if (!oldPassword.equals(password)) {
                JOptionPane.showMessageDialog(null, "There Is Wrong In Old Password ❌");
            }
            // أن يكون عدد أحرف كلمة السر أقل من ثمانية أحرف
            else if (newPassword.length() < 8) {
                JOptionPane.showMessageDialog(null, "The Password Must Be 8 Litters Or More ❌");
            }
            // ان تكون كلمة السر الجديدة تساوي كلمة السر الحالية
            else if (newPassword.equals(oldPassword)) {
                JOptionPane.showMessageDialog(null, "The New Password Mustn't Equals Old Password ❌");
            }
            // احتواء كلمة السر على بعض الرموز
            else if (newPassword.contains("(") || newPassword.contains(")") || newPassword.contains("{")
                    || newPassword.contains("}") || newPassword.contains("[") || newPassword.contains("]")
                    || newPassword.contains(" ")) {
                JOptionPane.showMessageDialog(null, "The New Password Mustn't Contains spaces,(,),{,},[,] ❌");
            }
            // منطق تغيير كلمة المرور
            else {
                JOptionPane.showMessageDialog(null, "The Password Has Changed Successfully ✔");
                // كتابة كلمة السر الجديدة في ملف معلومات المستخدم
                PrintWriter pw = new PrintWriter(f);
                pw.println("Password:" + newPassword);
                // كتابة الاسم الكامل للمستخدم في ملف المعلومات
                PrintWriter pw2 = new PrintWriter(new FileWriter(f, true));
                pw2.print("FullName:" + fullName);
                pw.flush();
                pw.close();
                pw2.flush();
                pw2.close();
                // الانتقال لواجهة الهوم
                Home home = new Home();
                home.setLocationRelativeTo(null);
                home.setVisible(true);
                this.dispose();

            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ChangePasswordFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ChangePasswordFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePasswordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField newPass;
    private javax.swing.JTextField oldPass;
    // End of variables declaration//GEN-END:variables
}
